[workspace]
git_only = true
publish = false

release = true
release_always = true

git_tag_name = "{{ package }}-v{{ version }}"
git_tag_enable = true

git_release_enable = false
changelog_update = false
semver_check = false

[[package]]
name = "lumen-cli"

git_tag_name = "v{{ version }}"
git_tag_enable = true

git_release_enable = true
git_release_name = "v{{ version }}"

changelog_update = true
changelog_path = "./CHANGELOG.md"

changelog_include = [
  "lumen-core",
  "lumen-media",
  "lumen-session",
  "lumen-server",
  "lumen-webrtc",
  "lumen-desktop",
]
